---
root: true
parser: babel-eslint
extends:
  - eslint-config-airbnb
plugins:
  - react-hooks
env:
  browser: true
  jest: true
rules:
  arrow-parens: off
  class-methods-use-this: off
  function-paren-newline: off
  guard-for-in: off
  implicit-arrow-linebreak: off
  max-len: off
  no-await-in-loop: off
  no-continue: off
  no-mixed-operators: off
  no-param-reassign: off
  no-plusplus: off
  no-restricted-syntax: off
  no-shadow: off
  no-underscore-dangle: off
  no-use-before-define: off
  import/prefer-default-export: off
  react/jsx-filename-extension: off
  react/jsx-one-expression-per-line: off
  react/jsx-props-no-spreading: off
  react/require-default-props: off
  prefer-spread: off

  array-bracket-spacing:
    - error
    - always
  brace-style:
    - error
    - stroustrup
  import/no-unresolved:
    - error
    -
      commonjs: true
      caseSensitive: true
      ignore: [^~]
  no-unused-vars:
    - error
    -
      ignoreRestSiblings: true
  object-curly-newline:
    - error
    -
      multiline: true
      consistent: true
  react/default-props-match-prop-types:
    - error
    -
      allowRequiredDefaults: true
  react-hooks/exhaustive-deps:
    - error
  react-hooks/rules-of-hooks:
    - error
