name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Precheck
        run: |
          npm ci
          npm run depcheck
          npm run eslint
          npm run typecheck

      - name: Build Library
        run: npm run build

      - name: Build Storybook
        run: npm run storybook:build

      - name: Deploy Storybook
        if: startsWith(github.ref, 'refs/tags/v')
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          user_name: "Workflow: ${{ env.GITHUB_WORKFLOW }}[bot]"
          user_email: "${{ env.GITHUB_WORKFLOW }}[bot]@workflow"
          publish_dir: ./_storybook

      - name: Publish Library
        if: startsWith(github.ref, 'refs/tags/v')
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Notify Slack for Failures
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ci
          status: FAILED
          color: danger
