name: Publish

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Version segment to increment"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Precheck
        run: |
          npm ci
          npm run depcheck
          npm run eslint
          npm run typecheck

      - name: Build Library
        run: npm run build

      - name: Build Storybook
        run: npm run storybook:build

      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: "Workflow: ${{ env.GITHUB_WORKFLOW }}[bot]"
          user_email: "${{ env.GITHUB_WORKFLOW }}[bot]@workflow"
          publish_dir: ./_storybook

      - name: Increment Version
        run: |
          git config --local user.email "Workflow: ${{ env.GITHUB_WORKFLOW }}[bot]"
          git config --local user.name "${{ env.GITHUB_WORKFLOW }}[bot]@workflow"
          npm version ${{ github.event.inputs.type }} -m "Publish v%s"

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Push Tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Notify Slack for Failures
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ci
          status: FAILED
          color: danger
